data:
  target: dataset.data_module.DataModule
  params:
    # Path to training set configuration file.
    train_config: config/dataset/exposure_errors_b4_train.yaml
    # Path to validation set configuration file.
    val_config: config/dataset/exposure_errors_b4_val.yaml

model:
  target: model.uformer.uformer_module.UFormerModule
  params:
    arch: Uformer_B
    dd_in: 3
    train_ps: 128
    lr: 0.0001
    optimizer: adamw
    warmup: True
    weight_decay: 0.02

lightning:
  seed: 231
  
  trainer:
    accelerator: cuda
    precision: 32
    strategy: ddp_find_unused_parameters_true
    # Indices of GPUs used for training.
    devices: 4
    # Path to save logs and checkpoints.
    default_root_dir: outputs
    # Max number of training steps (batches).
    max_steps: 25001
    # Validation frequency in terms of training steps.
    val_check_interval: 100
    check_val_every_n_epoch:
    log_every_n_steps: 50
    # Accumulate gradients from multiple batches so as to increase batch size.
    accumulate_grad_batches: 4
  
  logger:
    target: logger.tensorboard_logger.TensorBoardLogger
    params:
      save_dir: train_viz
      name: uformer_exposure_errors
  
  callbacks:
    - target: callback.image_logger.ImageLogger
      params:
        # Log frequency of image logger.
        log_every_n_steps: 1
        max_images_each_step: 4
        log_images_kwargs: ~

    - target: callback.model_checkpoint.ModelCheckpoint
      params:
        # Frequency of saving checkpoints.
        every_n_train_steps: 1000
        save_top_k: -1
        filename: "{step}"
