data:
  target: dataset.data_module.DataModule
  params:
    # Path to training set configuration file.
    train_config: config/dataset/tunnel_defect_train.yaml
    # Path to validation set configuration file.
    val_config: config/dataset/tunnel_defect_val.yaml

model:
  target: model.segformer.segformer_module.SegFormerModule
  checkpoint: train_seg_viz/segformer_tunnel_defect/version_0/checkpoints/step=5000.ckpt
  params:
    lr: 0.0015
    num_classes: 3
    type_classes: ["background", "crack", "tile_peeling"]
    color_map: [[0, 0, 0], [255, 0, 0], [0, 255, 0]]
    pretrained: weight/segformer/pretrained/segformer_b0_backbone_weights.pth

lightning:
  seed: 231
  
  trainer:
    accelerator: cuda
    precision: 32
    strategy: ddp_find_unused_parameters_true
    # Indices of GPUs used for training.
    devices: 4
    # Path to save logs and checkpoints.
    default_root_dir: outputs
    # Max number of training steps (batches).
    max_steps: 10000
    # Validation frequency in terms of training steps.
    val_check_interval: 100
    check_val_every_n_epoch:
    log_every_n_steps: 50
    # Accumulate gradients from multiple batches so as to increase batch size.
    accumulate_grad_batches: 1
  
  logger:
    target: logger.tensorboard_logger.TensorBoardLogger
    params:
      save_dir: test_seg_viz
      name: segformer_tunnel_defect
  
  callbacks:
    - target: callback.image_logger.ImageLogger
      params:
        # Log frequency of image logger.
        log_every_n_steps: 1
        max_images_each_step: 4
        log_images_kwargs: ~

    - target: callback.model_checkpoint.ModelCheckpoint
      params:
        # Frequency of saving checkpoints.
        every_n_train_steps: 1000
        save_top_k: -1
        filename: "{step}"
