dataset:
  target: dataset.tunnel_defect.TunnelDefectDataset
  params:
    file_list: /home/lib/tunnel_diff/0_pl_module/config/dataset/tunnel_defect_enhance/val.txt
    image_root: /home/lib/tunnel_diff/0_pl_module/test_viz/zero_dce_tunnel_defect/test-1711818831.243914_image
    annotation_root: /home/datasets/tunnel-defect-v5-patch2/annotations/validation
    image_format: png
    annotation_format: png
    out_size: 512
    apply_transform: false

data_loader:
  batch_size: 16
  shuffle: false
  num_workers: 16
  drop_last: false
